//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Managements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Managements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Managements", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abuses.
        /// </summary>
        internal static string Abuses {
            get {
                return ResourceManager.GetString("Abuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Abuse_Copyright {
            get {
                return ResourceManager.GetString("Abuse_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hate speech or violence.
        /// </summary>
        internal static string Abuse_HateSpeech {
            get {
                return ResourceManager.GetString("Abuse_HateSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudity.
        /// </summary>
        internal static string Abuse_Nudity {
            get {
                return ResourceManager.GetString("Abuse_Nudity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why are you reporting this post?Thank you for helping us by reporting content which may be in violation of our Community Standards..
        /// </summary>
        internal static string Abuse_ReportReason {
            get {
                return ResourceManager.GetString("Abuse_ReportReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your helping.
        /// </summary>
        internal static string Abuse_ThxForHelping {
            get {
                return ResourceManager.GetString("Abuse_ThxForHelping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report is send to our administrator.Thank you for helping us by reporting content which may be in violation of our Community Standards..
        /// </summary>
        internal static string Abuse_ThxForReporting {
            get {
                return ResourceManager.GetString("Abuse_ThxForReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rule.
        /// </summary>
        internal static string AddRule {
            get {
                return ResourceManager.GetString("AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator dashboard.
        /// </summary>
        internal static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow register new user.
        /// </summary>
        internal static string AllowRegisterNewUser {
            get {
                return ResourceManager.GetString("AllowRegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow upload file types.
        /// </summary>
        internal static string AllowUploadFileTypes {
            get {
                return ResourceManager.GetString("AllowUploadFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing App ID.
        /// </summary>
        internal static string BingAppID {
            get {
                return ResourceManager.GetString("BingAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing verifcation key.
        /// </summary>
        internal static string BingVerifyKey {
            get {
                return ResourceManager.GetString("BingVerifyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePwd {
            get {
                return ResourceManager.GetString("ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create localize copy.
        /// </summary>
        internal static string CreateLocCopy {
            get {
                return ResourceManager.GetString("CreateLocCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        internal static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default netdrive used quota.
        /// </summary>
        internal static string DefaultNetDriveQuota {
            get {
                return ResourceManager.GetString("DefaultNetDriveQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default langauge.
        /// </summary>
        internal static string DefLang {
            get {
                return ResourceManager.GetString("DefLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories and Files.
        /// </summary>
        internal static string DirsAndFiles {
            get {
                return ResourceManager.GetString("DirsAndFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;If you want this rule to affect all files and directories, type /.&lt;/div&gt;&lt;div&gt; To specify individual files or directories, type them in one per line. Example: &lt;div&gt;&lt;div&gt;/directory/file.html&lt;/div&gt;&lt;div&gt;/directory/subdirectory/&lt;/div&gt;.
        /// </summary>
        internal static string DirsAndFilesNotes {
            get {
                return ResourceManager.GetString("DirsAndFilesNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNetAge account.
        /// </summary>
        internal static string DNAAccount {
            get {
                return ResourceManager.GetString("DNAAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sitemenu.
        /// </summary>
        internal static string EnableSitemenu {
            get {
                return ResourceManager.GetString("EnableSitemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableSsl.
        /// </summary>
        internal static string EnableSsl {
            get {
                return ResourceManager.GetString("EnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook OAuth settings.
        /// </summary>
        internal static string FbSettings {
            get {
                return ResourceManager.GetString("FbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field settings.
        /// </summary>
        internal static string FieldSettings {
            get {
                return ResourceManager.GetString("FieldSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force email validation.
        /// </summary>
        internal static string ForceEmailValidation {
            get {
                return ResourceManager.GetString("ForceEmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full trust.
        /// </summary>
        internal static string FullTrust {
            get {
                return ResourceManager.GetString("FullTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google analytics account.
        /// </summary>
        internal static string GAAccount {
            get {
                return ResourceManager.GetString("GAAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings.
        /// </summary>
        internal static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google verification key.
        /// </summary>
        internal static string GoogleVerifyKey {
            get {
                return ResourceManager.GetString("GoogleVerifyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google+ OAuth settings.
        /// </summary>
        internal static string GPlusSettings {
            get {
                return ResourceManager.GetString("GPlusSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host account.
        /// </summary>
        internal static string HostAccount {
            get {
                return ResourceManager.GetString("HostAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install solution after user register.
        /// </summary>
        internal static string InstallSolAfterReg {
            get {
                return ResourceManager.GetString("InstallSolAfterReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium trust.
        /// </summary>
        internal static string MediumTrust {
            get {
                return ResourceManager.GetString("MediumTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metas.
        /// </summary>
        internal static string Metas {
            get {
                return ResourceManager.GetString("Metas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta tags.
        /// </summary>
        internal static string MetaTags {
            get {
                return ResourceManager.GetString("MetaTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum password length.
        /// </summary>
        internal static string MinPwdLen {
            get {
                return ResourceManager.GetString("MinPwdLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum user name length.
        /// </summary>
        internal static string MinUserNameLen {
            get {
                return ResourceManager.GetString("MinUserNameLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetDriver.
        /// </summary>
        internal static string NetDriver {
            get {
                return ResourceManager.GetString("NetDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network accounts.
        /// </summary>
        internal static string Networkaccounts {
            get {
                return ResourceManager.GetString("Networkaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal settings.
        /// </summary>
        internal static string PersonalSettings {
            get {
                return ResourceManager.GetString("PersonalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the size of pre upload file.
        /// </summary>
        internal static string PreUploadFileSize {
            get {
                return ResourceManager.GetString("PreUploadFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCaptcha.
        /// </summary>
        internal static string ReCaptcha {
            get {
                return ResourceManager.GetString("ReCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCaptcha PrivateKey.
        /// </summary>
        internal static string ReCaptchaPrivateKey {
            get {
                return ResourceManager.GetString("ReCaptchaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCaptcha PublicKey.
        /// </summary>
        internal static string ReCaptchaPublicKey {
            get {
                return ResourceManager.GetString("ReCaptchaPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        internal static string Reporter {
            get {
                return ResourceManager.GetString("Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved user names.
        /// </summary>
        internal static string ReservedUserNames {
            get {
                return ResourceManager.GetString("ReservedUserNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to robot.txt.
        /// </summary>
        internal static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap url.
        /// </summary>
        internal static string SitemapUrl {
            get {
                return ResourceManager.GetString("SitemapUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site settings.
        /// </summary>
        internal static string SiteSettings {
            get {
                return ResourceManager.GetString("SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender name.
        /// </summary>
        internal static string Smtp_DispName {
            get {
                return ResourceManager.GetString("Smtp_DispName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender account.
        /// </summary>
        internal static string Smtp_Sender {
            get {
                return ResourceManager.GetString("Smtp_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp server.
        /// </summary>
        internal static string Smtp_Server {
            get {
                return ResourceManager.GetString("Smtp_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Settings.
        /// </summary>
        internal static string SMTP_Settings {
            get {
                return ResourceManager.GetString("SMTP_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        internal static string Spam {
            get {
                return ResourceManager.GetString("Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify additional metas.
        /// </summary>
        internal static string SpecifyAdditionalMetas {
            get {
                return ResourceManager.GetString("SpecifyAdditionalMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify additional rules.
        /// </summary>
        internal static string SpecifyRules {
            get {
                return ResourceManager.GetString("SpecifyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch default language.
        /// </summary>
        internal static string SwitchToDefault {
            get {
                return ResourceManager.GetString("SwitchToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task pane.
        /// </summary>
        internal static string TaskPane {
            get {
                return ResourceManager.GetString("TaskPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr OAuth settings.
        /// </summary>
        internal static string TRSettings {
            get {
                return ResourceManager.GetString("TRSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust level.
        /// </summary>
        internal static string TrustLevel {
            get {
                return ResourceManager.GetString("TrustLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter OAuth settings.
        /// </summary>
        internal static string TWSettings {
            get {
                return ResourceManager.GetString("TWSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Full trust level.
        /// </summary>
        internal static string UnlockFullTrust {
            get {
                return ResourceManager.GetString("UnlockFullTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used default credentials.
        /// </summary>
        internal static string UseDefaultCredentials {
            get {
                return ResourceManager.GetString("UseDefaultCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration.
        /// </summary>
        internal static string UserRegistration {
            get {
                return ResourceManager.GetString("UserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View settings.
        /// </summary>
        internal static string ViewSettings {
            get {
                return ResourceManager.GetString("ViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web master tools.
        /// </summary>
        internal static string WebMasterTools {
            get {
                return ResourceManager.GetString("WebMasterTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website settings.
        /// </summary>
        internal static string WebSiteSettings {
            get {
                return ResourceManager.GetString("WebSiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsLive OAuth settings.
        /// </summary>
        internal static string WLSettings {
            get {
                return ResourceManager.GetString("WLSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve www.
        /// </summary>
        internal static string WWWResolved {
            get {
                return ResourceManager.GetString("WWWResolved", resourceCulture);
            }
        }
    }
}
