//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Designs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Designs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Designs", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        internal static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add images.
        /// </summary>
        internal static string AddImages {
            get {
                return ResourceManager.GetString("AddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add page.
        /// </summary>
        internal static string AddPage {
            get {
                return ResourceManager.GetString("AddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        internal static string ChanageTheme {
            get {
                return ResourceManager.GetString("ChanageTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Css class.
        /// </summary>
        internal static string ClsName {
            get {
                return ResourceManager.GetString("ClsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayMode.
        /// </summary>
        internal static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        internal static string DoNothing {
            get {
                return ResourceManager.GetString("DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit stylesheet.
        /// </summary>
        internal static string EditCss {
            get {
                return ResourceManager.GetString("EditCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font family.
        /// </summary>
        internal static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FontSze {
            get {
                return ResourceManager.GetString("FontSze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to specified link.
        /// </summary>
        internal static string GoToLink {
            get {
                return ResourceManager.GetString("GoToLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid layout.
        /// </summary>
        internal static string GridLayout {
            get {
                return ResourceManager.GetString("GridLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImagePosition.
        /// </summary>
        internal static string ImagePosition {
            get {
                return ResourceManager.GetString("ImagePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image scaling.
        /// </summary>
        internal static string ImageScaling {
            get {
                return ResourceManager.GetString("ImageScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size.
        /// </summary>
        internal static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image title.
        /// </summary>
        internal static string ImageTitle {
            get {
                return ResourceManager.GetString("ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom size ....
        /// </summary>
        internal static string ImgSize_Custom {
            get {
                return ResourceManager.GetString("ImgSize_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large : 800 px width.
        /// </summary>
        internal static string ImgSize_Large {
            get {
                return ResourceManager.GetString("ImgSize_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium : 500 px width.
        /// </summary>
        internal static string ImgSize_Medium {
            get {
                return ResourceManager.GetString("ImgSize_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original size.
        /// </summary>
        internal static string ImgSize_Original {
            get {
                return ResourceManager.GetString("ImgSize_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small : 240 px width.
        /// </summary>
        internal static string ImgSize_Small {
            get {
                return ResourceManager.GetString("ImgSize_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail : 100 px width.
        /// </summary>
        internal static string ImgSize_Thumb {
            get {
                return ResourceManager.GetString("ImgSize_Thumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouts.
        /// </summary>
        internal static string Layouts {
            get {
                return ResourceManager.GetString("Layouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo and title.
        /// </summary>
        internal static string LogoAndTitle {
            get {
                return ResourceManager.GetString("LogoAndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo only.
        /// </summary>
        internal static string LogoOnly {
            get {
                return ResourceManager.GetString("LogoOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left to right (ltr).
        /// </summary>
        internal static string LTR {
            get {
                return ResourceManager.GetString("LTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max height.
        /// </summary>
        internal static string MaxHeight {
            get {
                return ResourceManager.GetString("MaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max width.
        /// </summary>
        internal static string MaxWidth {
            get {
                return ResourceManager.GetString("MaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min height.
        /// </summary>
        internal static string MinHeight {
            get {
                return ResourceManager.GetString("MinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min width.
        /// </summary>
        internal static string MinWidth {
            get {
                return ResourceManager.GetString("MinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No follow.
        /// </summary>
        internal static string Nofollow {
            get {
                return ResourceManager.GetString("Nofollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image viewer.
        /// </summary>
        internal static string OpenImageViewer {
            get {
                return ResourceManager.GetString("OpenImageViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize images.
        /// </summary>
        internal static string OrganizeImages {
            get {
                return ResourceManager.GetString("OrganizeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string Padding {
            get {
                return ResourceManager.GetString("Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to left (rtl).
        /// </summary>
        internal static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        internal static string Scaling_Fit {
            get {
                return ResourceManager.GetString("Scaling_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Scaling_Full {
            get {
                return ResourceManager.GetString("Scaling_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Scaling_Normal {
            get {
                return ResourceManager.GetString("Scaling_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator.
        /// </summary>
        internal static string Simulator {
            get {
                return ResourceManager.GetString("Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing.
        /// </summary>
        internal static string Sizing {
            get {
                return ResourceManager.GetString("Sizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces.
        /// </summary>
        internal static string Spaces {
            get {
                return ResourceManager.GetString("Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New window.
        /// </summary>
        internal static string Target_Blank {
            get {
                return ResourceManager.GetString("Target_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent window.
        /// </summary>
        internal static string Target_Parent {
            get {
                return ResourceManager.GetString("Target_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current window.
        /// </summary>
        internal static string Target_Self {
            get {
                return ResourceManager.GetString("Target_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top window.
        /// </summary>
        internal static string Target_Top {
            get {
                return ResourceManager.GetString("Target_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text position.
        /// </summary>
        internal static string TextPosition {
            get {
                return ResourceManager.GetString("TextPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title layout.
        /// </summary>
        internal static string TitleLayout {
            get {
                return ResourceManager.GetString("TitleLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title only.
        /// </summary>
        internal static string TitleOnly {
            get {
                return ResourceManager.GetString("TitleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewMode.
        /// </summary>
        internal static string ViewMode {
            get {
                return ResourceManager.GetString("ViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When clicking on image.
        /// </summary>
        internal static string WhenClickOnImage {
            get {
                return ResourceManager.GetString("WhenClickOnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
