//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Pages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add page.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add content.
        /// </summary>
        internal static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link.
        /// </summary>
        internal static string AddLink {
            get {
                return ResourceManager.GetString("AddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the page to allow the anonymous access. If uncheck this option ,the anonymous will be redirect to the login page..
        /// </summary>
        internal static string AllowAnonymousNotes {
            get {
                return ResourceManager.GetString("AllowAnonymousNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All webs.
        /// </summary>
        internal static string AllWebs {
            get {
                return ResourceManager.GetString("AllWebs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        internal static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing.
        /// </summary>
        internal static string Analyzing {
            get {
                return ResourceManager.GetString("Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom zone.
        /// </summary>
        internal static string BottomZone {
            get {
                return ResourceManager.GetString("BottomZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change layout.
        /// </summary>
        internal static string ChangeLayout {
            get {
                return ResourceManager.GetString("ChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        internal static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main zone.
        /// </summary>
        internal static string ContentZone {
            get {
                return ResourceManager.GetString("ContentZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new page.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create web.
        /// </summary>
        internal static string CreateWeb {
            get {
                return ResourceManager.GetString("CreateWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new page.
        /// </summary>
        internal static string CreatingPage {
            get {
                return ResourceManager.GetString("CreatingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current layout.
        /// </summary>
        internal static string CurrentLayout {
            get {
                return ResourceManager.GetString("CurrentLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design page.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design layout.
        /// </summary>
        internal static string DesignLayout {
            get {
                return ResourceManager.GetString("DesignLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the layout from following list and drop to page to add new layout.
        /// </summary>
        internal static string DragDropToAddLayout {
            get {
                return ResourceManager.GetString("DragDropToAddLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit css style.
        /// </summary>
        internal static string EditCss {
            get {
                return ResourceManager.GetString("EditCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit html.
        /// </summary>
        internal static string EditHtml {
            get {
                return ResourceManager.GetString("EditHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit startup scripts.
        /// </summary>
        internal static string EditScript {
            get {
                return ResourceManager.GetString("EditScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit page settings.
        /// </summary>
        internal static string EditSettings {
            get {
                return ResourceManager.GetString("EditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract keywords.
        /// </summary>
        internal static string ExtractKeywords {
            get {
                return ResourceManager.GetString("ExtractKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer center zone.
        /// </summary>
        internal static string FooterCenterZone {
            get {
                return ResourceManager.GetString("FooterCenterZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer left zone.
        /// </summary>
        internal static string FooterLeftZone {
            get {
                return ResourceManager.GetString("FooterLeftZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer right zone.
        /// </summary>
        internal static string FooterRightZone {
            get {
                return ResourceManager.GetString("FooterRightZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer zone.
        /// </summary>
        internal static string FooterZone {
            get {
                return ResourceManager.GetString("FooterZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header zone.
        /// </summary>
        internal static string HeaderZone {
            get {
                return ResourceManager.GetString("HeaderZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install solution.
        /// </summary>
        internal static string InstallSolution {
            get {
                return ResourceManager.GetString("InstallSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Layout.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left zone.
        /// </summary>
        internal static string LeftZone {
            get {
                return ResourceManager.GetString("LeftZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle zone.
        /// </summary>
        internal static string MidZone {
            get {
                return ResourceManager.GetString("MidZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My webs.
        /// </summary>
        internal static string MyWebs {
            get {
                return ResourceManager.GetString("MyWebs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigator zone.
        /// </summary>
        internal static string NavigationZone {
            get {
                return ResourceManager.GetString("NavigationZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to.
        /// </summary>
        internal static string NavTo {
            get {
                return ResourceManager.GetString("NavTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        internal static string OpenInNewWin {
            get {
                return ResourceManager.GetString("OpenInNewWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting to new page.
        /// </summary>
        internal static string RedirectingToPage {
            get {
                return ResourceManager.GetString("RedirectingToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect url.
        /// </summary>
        internal static string RedirectUrl {
            get {
                return ResourceManager.GetString("RedirectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset layout.
        /// </summary>
        internal static string ResetLayout {
            get {
                return ResourceManager.GetString("ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right zone.
        /// </summary>
        internal static string RightZone {
            get {
                return ResourceManager.GetString("RightZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in menu.
        /// </summary>
        internal static string ShowInMenu {
            get {
                return ResourceManager.GetString("ShowInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in sitemap.
        /// </summary>
        internal static string ShowInSitemap {
            get {
                return ResourceManager.GetString("ShowInSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under current page.
        /// </summary>
        internal static string UnderCurrentPage {
            get {
                return ResourceManager.GetString("UnderCurrentPage", resourceCulture);
            }
        }
    }
}
