//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Contents", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new list.
        /// </summary>
        internal static string AddNewList {
            get {
                return ResourceManager.GetString("AddNewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields class.
        /// </summary>
        internal static string AllFieldsCls {
            get {
                return ResourceManager.GetString("AllFieldsCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow attachments.
        /// </summary>
        internal static string AllowAttachs {
            get {
                return ResourceManager.GetString("AllowAttachs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow categories &amp; tags.
        /// </summary>
        internal static string AllowCats {
            get {
                return ResourceManager.GetString("AllowCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow comments.
        /// </summary>
        internal static string AllowComments {
            get {
                return ResourceManager.GetString("AllowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow filtering.
        /// </summary>
        internal static string AllowFilter {
            get {
                return ResourceManager.GetString("AllowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow html.
        /// </summary>
        internal static string AllowHtml {
            get {
                return ResourceManager.GetString("AllowHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multi-choice.
        /// </summary>
        internal static string AllowMultiChoice {
            get {
                return ResourceManager.GetString("AllowMultiChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow paging.
        /// </summary>
        internal static string AllowPaging {
            get {
                return ResourceManager.GetString("AllowPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow re-share.
        /// </summary>
        internal static string AllowReshare {
            get {
                return ResourceManager.GetString("AllowReshare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow sorting.
        /// </summary>
        internal static string AllowSorting {
            get {
                return ResourceManager.GetString("AllowSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow votes.
        /// </summary>
        internal static string AllowVotes {
            get {
                return ResourceManager.GetString("AllowVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation.
        /// </summary>
        internal static string Annotation {
            get {
                return ResourceManager.GetString("Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        internal static string Archives {
            get {
                return ResourceManager.GetString("Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asc.
        /// </summary>
        internal static string Asc {
            get {
                return ResourceManager.GetString("Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup files.
        /// </summary>
        internal static string BackupFiles {
            get {
                return ResourceManager.GetString("BackupFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No.
        /// </summary>
        internal static string BooleanField {
            get {
                return ResourceManager.GetString("BooleanField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories and Tags.
        /// </summary>
        internal static string CategoriesAndTags {
            get {
                return ResourceManager.GetString("CategoriesAndTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        internal static string ChoiceField {
            get {
                return ResourceManager.GetString("ChoiceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the choice item(s) here.Each row holds one item..
        /// </summary>
        internal static string ChoiceFieldHolder {
            get {
                return ResourceManager.GetString("ChoiceFieldHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice items.
        /// </summary>
        internal static string ChoiceItems {
            get {
                return ResourceManager.GetString("ChoiceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuomputed.
        /// </summary>
        internal static string ComputedField {
            get {
                return ResourceManager.GetString("ComputedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content store.
        /// </summary>
        internal static string ContentStore {
            get {
                return ResourceManager.GetString("ContentStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentTypes.
        /// </summary>
        internal static string ContentTypes {
            get {
                return ResourceManager.GetString("ContentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating field.
        /// </summary>
        internal static string CreatingField {
            get {
                return ResourceManager.GetString("CreatingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string CurrencyField {
            get {
                return ResourceManager.GetString("CurrencyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item.
        /// </summary>
        internal static string DataItem {
            get {
                return ResourceManager.GetString("DataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; time.
        /// </summary>
        internal static string DateTimeField {
            get {
                return ResourceManager.GetString("DateTimeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default paging size.
        /// </summary>
        internal static string DefaultPagingSize {
            get {
                return ResourceManager.GetString("DefaultPagingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined.
        /// </summary>
        internal static string Defined {
            get {
                return ResourceManager.GetString("Defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this list.
        /// </summary>
        internal static string DeleteList {
            get {
                return ResourceManager.GetString("DeleteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting field from list.
        /// </summary>
        internal static string DeletingField {
            get {
                return ResourceManager.GetString("DeletingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable comments.
        /// </summary>
        internal static string DisableComments {
            get {
                return ResourceManager.GetString("DisableComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display as.
        /// </summary>
        internal static string DisplayAs {
            get {
                return ResourceManager.GetString("DisplayAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display style.
        /// </summary>
        internal static string DisplayStyle {
            get {
                return ResourceManager.GetString("DisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown list.
        /// </summary>
        internal static string DropDownlist {
            get {
                return ResourceManager.GetString("DropDownlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit source code.
        /// </summary>
        internal static string EditSrc {
            get {
                return ResourceManager.GetString("EditSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable comments.
        /// </summary>
        internal static string EnableComments {
            get {
                return ResourceManager.GetString("EnableComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable moderate.
        /// </summary>
        internal static string EnableModerate {
            get {
                return ResourceManager.GetString("EnableModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable versioning.
        /// </summary>
        internal static string EnableVersioning {
            get {
                return ResourceManager.GetString("EnableVersioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string Endswith {
            get {
                return ResourceManager.GetString("Endswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        internal static string Eq {
            get {
                return ResourceManager.GetString("Eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandable list.
        /// </summary>
        internal static string ExpandableList {
            get {
                return ResourceManager.GetString("ExpandableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object ExpandableListDesc {
            get {
                object obj = ResourceManager.GetObject("ExpandableListDesc", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        internal static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string ExtensionField {
            get {
                return ResourceManager.GetString("ExtensionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind to feed (rss,atom).
        /// </summary>
        internal static string FeedField {
            get {
                return ResourceManager.GetString("FeedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field settings.
        /// </summary>
        internal static string FieldSettings {
            get {
                return ResourceManager.GetString("FieldSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string FieldType {
            get {
                return ResourceManager.GetString("FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileField {
            get {
                return ResourceManager.GetString("FileField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in choice.
        /// </summary>
        internal static string FillInChoice {
            get {
                return ResourceManager.GetString("FillInChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form class.
        /// </summary>
        internal static string FormCls {
            get {
                return ResourceManager.GetString("FormCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form settings.
        /// </summary>
        internal static string FormSettings {
            get {
                return ResourceManager.GetString("FormSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show label - Show the field title text on the left of the value/editor.
        /// </summary>
        internal static string Form_ShowLabel {
            get {
                return ResourceManager.GetString("Form_ShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater then or equal to.
        /// </summary>
        internal static string Ge {
            get {
                return ResourceManager.GetString("Ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid view.
        /// </summary>
        internal static string GridView {
            get {
                return ResourceManager.GetString("GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be use for show image items..
        /// </summary>
        internal static string GridViewDesc {
            get {
                return ResourceManager.GetString("GridViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater then.
        /// </summary>
        internal static string Gt {
            get {
                return ResourceManager.GetString("Gt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageField {
            get {
                return ResourceManager.GetString("ImageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert class.
        /// </summary>
        internal static string InsertCls {
            get {
                return ResourceManager.GetString("InsertCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string IntegerField {
            get {
                return ResourceManager.GetString("IntegerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is hidden - Hide output value.
        /// </summary>
        internal static string IsHiddenField {
            get {
                return ResourceManager.GetString("IsHiddenField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is hierarchy data.
        /// </summary>
        internal static string IsHierarchyData {
            get {
                return ResourceManager.GetString("IsHierarchyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPublished.
        /// </summary>
        internal static string IsPublished {
            get {
                return ResourceManager.GetString("IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is required.
        /// </summary>
        internal static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item footer class.
        /// </summary>
        internal static string ItemFooterCls {
            get {
                return ResourceManager.GetString("ItemFooterCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item class.
        /// </summary>
        internal static string ItemsCls {
            get {
                return ResourceManager.GetString("ItemsCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less then or equal to.
        /// </summary>
        internal static string Le {
            get {
                return ResourceManager.GetString("Le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link list.
        /// </summary>
        internal static string LinkList {
            get {
                return ResourceManager.GetString("LinkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object LinkListDesc {
            get {
                object obj = ResourceManager.GetObject("LinkListDesc", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to item.
        /// </summary>
        internal static string LinkToItem {
            get {
                return ResourceManager.GetString("LinkToItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        internal static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List view.
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListViewDesc.
        /// </summary>
        internal static string ListViewDesc {
            get {
                return ResourceManager.GetString("ListViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading photo ....
        /// </summary>
        internal static string LoadingPhoto {
            get {
                return ResourceManager.GetString("LoadingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup.
        /// </summary>
        internal static string LookupField {
            get {
                return ResourceManager.GetString("LookupField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less then.
        /// </summary>
        internal static string Lt {
            get {
                return ResourceManager.GetString("Lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length.
        /// </summary>
        internal static string MaxLen {
            get {
                return ResourceManager.GetString("MaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a vaild max length value.
        /// </summary>
        internal static string MaxLenVal {
            get {
                return ResourceManager.GetString("MaxLenVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu view.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the data items in a menu.
        /// </summary>
        internal static string MenuViewDesc {
            get {
                return ResourceManager.GetString("MenuViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length.
        /// </summary>
        internal static string MinLen {
            get {
                return ResourceManager.GetString("MinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile listview.
        /// </summary>
        internal static string MobileView {
            get {
                return ResourceManager.GetString("MobileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object MobileViewDesc {
            get {
                object obj = ResourceManager.GetObject("MobileViewDesc", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate state.
        /// </summary>
        internal static string ModerateState {
            get {
                return ResourceManager.GetString("ModerateState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderators.
        /// </summary>
        internal static string Moderators {
            get {
                return ResourceManager.GetString("Moderators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My contents.
        /// </summary>
        internal static string MyContents {
            get {
                return ResourceManager.GetString("MyContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My drafts.
        /// </summary>
        internal static string MyDrafts {
            get {
                return ResourceManager.GetString("MyDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My items.
        /// </summary>
        internal static string MyItems {
            get {
                return ResourceManager.GetString("MyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My pending items.
        /// </summary>
        internal static string MyPendings {
            get {
                return ResourceManager.GetString("MyPendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My published items.
        /// </summary>
        internal static string MyPublishedItems {
            get {
                return ResourceManager.GetString("MyPublishedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show user name only.
        /// </summary>
        internal static string NameOnly {
            get {
                return ResourceManager.GetString("NameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t equal.
        /// </summary>
        internal static string Neq {
            get {
                return ResourceManager.GetString("Neq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New field.
        /// </summary>
        internal static string NewField {
            get {
                return ResourceManager.GetString("NewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create view.
        /// </summary>
        internal static string NewView {
            get {
                return ResourceManager.GetString("NewView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t create page for this view.
        /// </summary>
        internal static string NoPage {
            get {
                return ResourceManager.GetString("NoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t contain.
        /// </summary>
        internal static string NotContains {
            get {
                return ResourceManager.GetString("NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteField {
            get {
                return ResourceManager.GetString("NoteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not set.
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string NumberField {
            get {
                return ResourceManager.GetString("NumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers of lines.
        /// </summary>
        internal static string NumLines {
            get {
                return ResourceManager.GetString("NumLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open default view.
        /// </summary>
        internal static string OpenDefView {
            get {
                return ResourceManager.GetString("OpenDefView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index.
        /// </summary>
        internal static string PageIndex {
            get {
                return ResourceManager.GetString("PageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Item.
        /// </summary>
        internal static string ParentItem {
            get {
                return ResourceManager.GetString("ParentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending review.
        /// </summary>
        internal static string PendingReview {
            get {
                return ResourceManager.GetString("PendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show photo and name.
        /// </summary>
        internal static string PhotoAndName {
            get {
                return ResourceManager.GetString("PhotoAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show photo only.
        /// </summary>
        internal static string PhotoOnly {
            get {
                return ResourceManager.GetString("PhotoOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place holder.
        /// </summary>
        internal static string PlaceHolder {
            get {
                return ResourceManager.GetString("PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player height.
        /// </summary>
        internal static string PlayerHeight {
            get {
                return ResourceManager.GetString("PlayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player width.
        /// </summary>
        internal static string PlayerWidth {
            get {
                return ResourceManager.GetString("PlayerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishDate.
        /// </summary>
        internal static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to activity stream.
        /// </summary>
        internal static string PublishToActivityStream {
            get {
                return ResourceManager.GetString("PublishToActivityStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio buttons.
        /// </summary>
        internal static string RadioButtons {
            get {
                return ResourceManager.GetString("RadioButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this attachment.
        /// </summary>
        internal static string RemoveAttach {
            get {
                return ResourceManager.GetString("RemoveAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies.
        /// </summary>
        internal static string Replies {
            get {
                return ResourceManager.GetString("Replies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        internal static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show as percentage.
        /// </summary>
        internal static string ShowAsPercentage {
            get {
                return ResourceManager.GetString("ShowAsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page info.
        /// </summary>
        internal static string ShowPageInfo {
            get {
                return ResourceManager.GetString("ShowPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time.
        /// </summary>
        internal static string ShowTime {
            get {
                return ResourceManager.GetString("ShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider view.
        /// </summary>
        internal static string SliderView {
            get {
                return ResourceManager.GetString("SliderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object SliderViewDesc {
            get {
                object obj = ResourceManager.GetObject("SliderViewDesc", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide show.
        /// </summary>
        internal static string SlideShow {
            get {
                return ResourceManager.GetString("SlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object SlideShowDesc {
            get {
                object obj = ResourceManager.GetObject("SlideShowDesc", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page name is exists please choice another name.
        /// </summary>
        internal static string SlugIsExists {
            get {
                return ResourceManager.GetString("SlugIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page name is required.
        /// </summary>
        internal static string SlugIsRequired {
            get {
                return ResourceManager.GetString("SlugIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string Sortby {
            get {
                return ResourceManager.GetString("Sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splite comma with multiple tags.
        /// </summary>
        internal static string SpliteTags {
            get {
                return ResourceManager.GetString("SpliteTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        internal static string Startswith {
            get {
                return ResourceManager.GetString("Startswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style and layout.
        /// </summary>
        internal static string StyleAndLayout {
            get {
                return ResourceManager.GetString("StyleAndLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table view.
        /// </summary>
        internal static string TableView {
            get {
                return ResourceManager.GetString("TableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object TableViewDesc {
            get {
                object obj = ResourceManager.GetObject("TableViewDesc", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags group view.
        /// </summary>
        internal static string TagsView {
            get {
                return ResourceManager.GetString("TagsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by item tags.
        /// </summary>
        internal static string TagsViewDesc {
            get {
                return ResourceManager.GetString("TagsViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextField {
            get {
                return ResourceManager.GetString("TextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme store.
        /// </summary>
        internal static string ThemeStore {
            get {
                return ResourceManager.GetString("ThemeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail height.
        /// </summary>
        internal static string ThumbnailHeight {
            get {
                return ResourceManager.GetString("ThumbnailHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail width.
        /// </summary>
        internal static string ThumbnailWidth {
            get {
                return ResourceManager.GetString("ThumbnailWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLine.
        /// </summary>
        internal static string TimeLine {
            get {
                return ResourceManager.GetString("TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the view data in a timeline..
        /// </summary>
        internal static string TimeLineDesc {
            get {
                return ResourceManager.GetString("TimeLineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total attachements.
        /// </summary>
        internal static string TotalAttachs {
            get {
                return ResourceManager.GetString("TotalAttachs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total comments.
        /// </summary>
        internal static string TotalComms {
            get {
                return ResourceManager.GetString("TotalComms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reshares.
        /// </summary>
        internal static string TotalReshares {
            get {
                return ResourceManager.GetString("TotalReshares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total votes.
        /// </summary>
        internal static string TotalVotes {
            get {
                return ResourceManager.GetString("TotalVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish.
        /// </summary>
        internal static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User .
        /// </summary>
        internal static string UserField {
            get {
                return ResourceManager.GetString("UserField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User reviews.
        /// </summary>
        internal static string UserReviews {
            get {
                return ResourceManager.GetString("UserReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version history.
        /// </summary>
        internal static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string VideoField {
            get {
                return ResourceManager.GetString("VideoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View class.
        /// </summary>
        internal static string ViewCls {
            get {
                return ResourceManager.GetString("ViewCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View fields.
        /// </summary>
        internal static string ViewFields {
            get {
                return ResourceManager.GetString("ViewFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View items.
        /// </summary>
        internal static string ViewItems {
            get {
                return ResourceManager.GetString("ViewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show label - Show the field title text on the left of the view value.
        /// </summary>
        internal static string View_ShowLabel {
            get {
                return ResourceManager.GetString("View_ShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web store.
        /// </summary>
        internal static string WebStore {
            get {
                return ResourceManager.GetString("WebStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget store.
        /// </summary>
        internal static string WidgetStore {
            get {
                return ResourceManager.GetString("WidgetStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes text.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
