//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website settings have been saved.
        /// </summary>
        internal static string AfterWebSiteSaved {
            get {
                return ResourceManager.GetString("AfterWebSiteSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup complete..
        /// </summary>
        internal static string BackupComplete {
            get {
                return ResourceManager.GetString("BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failure.
        /// </summary>
        internal static string BackupFail {
            get {
                return ResourceManager.GetString("BackupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this web resource..
        /// </summary>
        internal static string CanNotDeleteWebRes {
            get {
                return ResourceManager.GetString("CanNotDeleteWebRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choice the layout of view.
        /// </summary>
        internal static string ChoiceLayoutOfView {
            get {
                return ResourceManager.GetString("ChoiceLayoutOfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure delete this {0} ?.
        /// </summary>
        internal static string ConfirmDelete_Format {
            get {
                return ResourceManager.GetString("ConfirmDelete_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure delete this layout and embded layouts?.
        /// </summary>
        internal static string Confirm_LayoutDelete {
            get {
                return ResourceManager.GetString("Confirm_LayoutDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure delete this page ? All widgets in this page will be delete too..
        /// </summary>
        internal static string Confirm_PageDelete {
            get {
                return ResourceManager.GetString("Confirm_PageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure reset this page layouts to default ?.
        /// </summary>
        internal static string Confirm_PageReset {
            get {
                return ResourceManager.GetString("Confirm_PageReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure rollback to this version?.
        /// </summary>
        internal static string Confirm_Rollback {
            get {
                return ResourceManager.GetString("Confirm_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email has been sent..
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email validation fail!.
        /// </summary>
        internal static string EmailValidFail {
            get {
                return ResourceManager.GetString("EmailValidFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email validation success!.
        /// </summary>
        internal static string EmailValidSuccess {
            get {
                return ResourceManager.GetString("EmailValidSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure {0} in your recipient list in order that you receive our password email..
        /// </summary>
        internal static string EnsureReceiver {
            get {
                return ResourceManager.GetString("EnsureReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re thrilled to have you aboard. Type in a password below to finalize your account..
        /// </summary>
        internal static string FinalizeAccountConnect {
            get {
                return ResourceManager.GetString("FinalizeAccountConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find the initial host password in web.config under your application root path..
        /// </summary>
        internal static string FindHostPwd {
            get {
                return ResourceManager.GetString("FindHostPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form fields has been changed please click the save button to submit changes..
        /// </summary>
        internal static string Form_FieldsIsChanged {
            get {
                return ResourceManager.GetString("Form_FieldsIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administrators has full permissions of the site..
        /// </summary>
        internal static string FullPermsOfAdmin {
            get {
                return ResourceManager.GetString("FullPermsOfAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To many images selected only top 10 images will be added..
        /// </summary>
        internal static string Gallery_TooManyImages {
            get {
                return ResourceManager.GetString("Gallery_TooManyImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no backup file found..
        /// </summary>
        internal static string NoBackupFile {
            get {
                return ResourceManager.GetString("NoBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item found..
        /// </summary>
        internal static string NoItemFound {
            get {
                return ResourceManager.GetString("NoItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No other languages..
        /// </summary>
        internal static string NoLangs {
            get {
                return ResourceManager.GetString("NoLangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile have been saved.
        /// </summary>
        internal static string ProfileSaved {
            get {
                return ResourceManager.GetString("ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply your register user name or email then we will send the password to your mailbox later..
        /// </summary>
        internal static string ReceivePwd {
            get {
                return ResourceManager.GetString("ReceivePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading permissions please wait.
        /// </summary>
        internal static string ReloadingPerms {
            get {
                return ResourceManager.GetString("ReloadingPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore successful.
        /// </summary>
        internal static string RestoreSuccess {
            get {
                return ResourceManager.GetString("RestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving smtp configurations.
        /// </summary>
        internal static string SavingSMTP {
            get {
                return ResourceManager.GetString("SavingSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security warnning.
        /// </summary>
        internal static string SecurityWarnning {
            get {
                return ResourceManager.GetString("SecurityWarnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image.
        /// </summary>
        internal static string SelectAnImage {
            get {
                return ResourceManager.GetString("SelectAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a {0}.
        /// </summary>
        internal static string SelectFormat {
            get {
                return ResourceManager.GetString("SelectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save smtp configuation failure..
        /// </summary>
        internal static string Smtp_Save_Fail {
            get {
                return ResourceManager.GetString("Smtp_Save_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save smtp settings success.
        /// </summary>
        internal static string Smtp_Save_Success {
            get {
                return ResourceManager.GetString("Smtp_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp testing fail!.
        /// </summary>
        internal static string Smtp_Test_Fail {
            get {
                return ResourceManager.GetString("Smtp_Test_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp test mail has send! Please check your email whether get this testing mail..
        /// </summary>
        internal static string Smtp_Test_Pass {
            get {
                return ResourceManager.GetString("Smtp_Test_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the name and title of the view.
        /// </summary>
        internal static string SupplyViewTitleAndName {
            get {
                return ResourceManager.GetString("SupplyViewTitleAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you change to Full trust mode please ensure whether your host environment is supported..
        /// </summary>
        internal static string TrustLevelWarnning {
            get {
                return ResourceManager.GetString("TrustLevelWarnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just need an user name and a password..
        /// </summary>
        internal static string UsrAndPwdRequire {
            get {
                return ResourceManager.GetString("UsrAndPwdRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or password not correct..
        /// </summary>
        internal static string UsrOrPwdInCorrect {
            get {
                return ResourceManager.GetString("UsrOrPwdInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view fields has been changed, you need to save the changed by manual..
        /// </summary>
        internal static string ViewFieldsChanged {
            get {
                return ResourceManager.GetString("ViewFieldsChanged", resourceCulture);
            }
        }
    }
}
