//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class perms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal perms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.perms", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add roles to user.
        /// </summary>
        internal static string SA_AddRolesToUser {
            get {
                return ResourceManager.GetString("SA_AddRolesToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to add roles for users.
        /// </summary>
        internal static string SA_AddRolesToUserDesc {
            get {
                return ResourceManager.GetString("SA_AddRolesToUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add widget to page.
        /// </summary>
        internal static string SA_AddWidget {
            get {
                return ResourceManager.GetString("SA_AddWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow add widgets to the page.
        /// </summary>
        internal static string SA_AddWidgetDesc {
            get {
                return ResourceManager.GetString("SA_AddWidgetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply widget settings.
        /// </summary>
        internal static string SA_ApplyWidgetSettings {
            get {
                return ResourceManager.GetString("SA_ApplyWidgetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to change common settings for widget.
        /// </summary>
        internal static string SA_ApplyWidgetSettingsDesc {
            get {
                return ResourceManager.GetString("SA_ApplyWidgetSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change icon and logo.
        /// </summary>
        internal static string SA_ChangeIconAndLogo {
            get {
                return ResourceManager.GetString("SA_ChangeIconAndLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can change the website title and logo..
        /// </summary>
        internal static string SA_ChangeIconAndLogoDesc {
            get {
                return ResourceManager.GetString("SA_ChangeIconAndLogoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change web site theme.
        /// </summary>
        internal static string SA_ChangeTheme {
            get {
                return ResourceManager.GetString("SA_ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can change the theme of current website..
        /// </summary>
        internal static string SA_ChangeThemeDesc {
            get {
                return ResourceManager.GetString("SA_ChangeThemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change themes.
        /// </summary>
        internal static string SA_ChangeThemes {
            get {
                return ResourceManager.GetString("SA_ChangeThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows change themes and web style.
        /// </summary>
        internal static string SA_ChangeThemesDesc {
            get {
                return ResourceManager.GetString("SA_ChangeThemesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup data.
        /// </summary>
        internal static string SA_ContentBackup {
            get {
                return ResourceManager.GetString("SA_ContentBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow users to backup list schema and data to file..
        /// </summary>
        internal static string SA_ContentBackupDesc {
            get {
                return ResourceManager.GetString("SA_ContentBackupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content manager.
        /// </summary>
        internal static string SA_ContentMan {
            get {
                return ResourceManager.GetString("SA_ContentMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users to use content manager.
        /// </summary>
        internal static string SA_ContentManDesc {
            get {
                return ResourceManager.GetString("SA_ContentManDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore data.
        /// </summary>
        internal static string SA_ContentRestore {
            get {
                return ResourceManager.GetString("SA_ContentRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users to recover views, forms, and data items from backup file..
        /// </summary>
        internal static string SA_ContentRestoreDesc {
            get {
                return ResourceManager.GetString("SA_ContentRestoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string SA_Contents {
            get {
                return ResourceManager.GetString("SA_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        internal static string SA_ControlPanel {
            get {
                return ResourceManager.GetString("SA_ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access to the control panel.
        /// </summary>
        internal static string SA_ControlPanelDesc {
            get {
                return ResourceManager.GetString("SA_ControlPanelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create category.
        /// </summary>
        internal static string SA_CreateCategory {
            get {
                return ResourceManager.GetString("SA_CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to create a new category.
        /// </summary>
        internal static string SA_CreateCategoryDesc {
            get {
                return ResourceManager.GetString("SA_CreateCategoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new list field.
        /// </summary>
        internal static string SA_CreateList {
            get {
                return ResourceManager.GetString("SA_CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user can be create new fields for list..
        /// </summary>
        internal static string SA_CreateListDesc {
            get {
                return ResourceManager.GetString("SA_CreateListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create page.
        /// </summary>
        internal static string SA_CreateNewPage {
            get {
                return ResourceManager.GetString("SA_CreateNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to create new web page.
        /// </summary>
        internal static string SA_CreateNewPageDesc {
            get {
                return ResourceManager.GetString("SA_CreateNewPageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new thread.
        /// </summary>
        internal static string SA_CreateNewThread {
            get {
                return ResourceManager.GetString("SA_CreateNewThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to create new thread.
        /// </summary>
        internal static string SA_CreateNewThreadDesc {
            get {
                return ResourceManager.GetString("SA_CreateNewThreadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create paths.
        /// </summary>
        internal static string SA_CreatePaths {
            get {
                return ResourceManager.GetString("SA_CreatePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to create directory on the server..
        /// </summary>
        internal static string SA_CreatePathsDesc {
            get {
                return ResourceManager.GetString("SA_CreatePathsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create roles.
        /// </summary>
        internal static string SA_CreateRoles {
            get {
                return ResourceManager.GetString("SA_CreateRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to add new role.
        /// </summary>
        internal static string SA_CreateRolesDesc {
            get {
                return ResourceManager.GetString("SA_CreateRolesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create team site.
        /// </summary>
        internal static string SA_CreateTeamSite {
            get {
                return ResourceManager.GetString("SA_CreateTeamSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can create new team site..
        /// </summary>
        internal static string SA_CreateTeamSiteDesc {
            get {
                return ResourceManager.GetString("SA_CreateTeamSiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create theme.
        /// </summary>
        internal static string SA_CreateTheme {
            get {
                return ResourceManager.GetString("SA_CreateTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can create new themes..
        /// </summary>
        internal static string SA_CreateThemeDesc {
            get {
                return ResourceManager.GetString("SA_CreateThemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create view.
        /// </summary>
        internal static string SA_CreateView {
            get {
                return ResourceManager.GetString("SA_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to create new views..
        /// </summary>
        internal static string SA_CreateViewDesc {
            get {
                return ResourceManager.GetString("SA_CreateViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new web.
        /// </summary>
        internal static string SA_CreateWeb {
            get {
                return ResourceManager.GetString("SA_CreateWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to create new web..
        /// </summary>
        internal static string SA_CreateWebDesc {
            get {
                return ResourceManager.GetString("SA_CreateWebDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create widget.
        /// </summary>
        internal static string SA_CreateWidget {
            get {
                return ResourceManager.GetString("SA_CreateWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users to create widgets by using widget editor..
        /// </summary>
        internal static string SA_CreateWidgetDesc {
            get {
                return ResourceManager.GetString("SA_CreateWidgetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete category.
        /// </summary>
        internal static string SA_DeleteCat {
            get {
                return ResourceManager.GetString("SA_DeleteCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to delete category.
        /// </summary>
        internal static string SA_DeleteCatDesc {
            get {
                return ResourceManager.GetString("SA_DeleteCatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete page.
        /// </summary>
        internal static string SA_DeletePage {
            get {
                return ResourceManager.GetString("SA_DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to delete page..
        /// </summary>
        internal static string SA_DeletePageDesc {
            get {
                return ResourceManager.GetString("SA_DeletePageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete paths.
        /// </summary>
        internal static string SA_DeletePaths {
            get {
                return ResourceManager.GetString("SA_DeletePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to delete the directory on the server..
        /// </summary>
        internal static string SA_DeletePathsDesc {
            get {
                return ResourceManager.GetString("SA_DeletePathsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete roles.
        /// </summary>
        internal static string SA_DeleteRoles {
            get {
                return ResourceManager.GetString("SA_DeleteRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to delete role.
        /// </summary>
        internal static string SA_DeleteRolesDesc {
            get {
                return ResourceManager.GetString("SA_DeleteRolesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete widgets.
        /// </summary>
        internal static string SA_DeleteWidget {
            get {
                return ResourceManager.GetString("SA_DeleteWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to delete widget.
        /// </summary>
        internal static string SA_DeleteWidgetDesc {
            get {
                return ResourceManager.GetString("SA_DeleteWidgetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete view.
        /// </summary>
        internal static string SA_DelView {
            get {
                return ResourceManager.GetString("SA_DelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to delete views..
        /// </summary>
        internal static string SA_DelViewDesc {
            get {
                return ResourceManager.GetString("SA_DelViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy packages.
        /// </summary>
        internal static string SA_DeployPackage {
            get {
                return ResourceManager.GetString("SA_DeployPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can deploy the uploaded packages..
        /// </summary>
        internal static string SA_DeployPackageDesc {
            get {
                return ResourceManager.GetString("SA_DeployPackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design page.
        /// </summary>
        internal static string SA_DesignPage {
            get {
                return ResourceManager.GetString("SA_DesignPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users to switch page design mode..
        /// </summary>
        internal static string SA_DesignPageDesc {
            get {
                return ResourceManager.GetString("SA_DesignPageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design themes.
        /// </summary>
        internal static string SA_DesignTheme {
            get {
                return ResourceManager.GetString("SA_DesignTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can use the style designer to design themes..
        /// </summary>
        internal static string SA_DesignThemeDesc {
            get {
                return ResourceManager.GetString("SA_DesignThemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download themes.
        /// </summary>
        internal static string SA_DownloadTheme {
            get {
                return ResourceManager.GetString("SA_DownloadTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can download the theme package..
        /// </summary>
        internal static string SA_DownloadThemeDesc {
            get {
                return ResourceManager.GetString("SA_DownloadThemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        internal static string SA_EditCat {
            get {
                return ResourceManager.GetString("SA_EditCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to edit category.
        /// </summary>
        internal static string SA_EditCatDesc {
            get {
                return ResourceManager.GetString("SA_EditCatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit list field.
        /// </summary>
        internal static string SA_EditField {
            get {
                return ResourceManager.GetString("SA_EditField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user can be edit the field settings..
        /// </summary>
        internal static string SA_EditFieldDesc {
            get {
                return ResourceManager.GetString("SA_EditFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit form.
        /// </summary>
        internal static string SA_EditForm {
            get {
                return ResourceManager.GetString("SA_EditForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user can custom forms..
        /// </summary>
        internal static string SA_EditFormDesc {
            get {
                return ResourceManager.GetString("SA_EditFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit list settings.
        /// </summary>
        internal static string SA_EditList {
            get {
                return ResourceManager.GetString("SA_EditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user can edit list settings and custom fields,views,and forms..
        /// </summary>
        internal static string SA_EditListDesc {
            get {
                return ResourceManager.GetString("SA_EditListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit page.
        /// </summary>
        internal static string SA_EditPage {
            get {
                return ResourceManager.GetString("SA_EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to edit page settings..
        /// </summary>
        internal static string SA_EditPageDesc {
            get {
                return ResourceManager.GetString("SA_EditPageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit view.
        /// </summary>
        internal static string SA_EditView {
            get {
                return ResourceManager.GetString("SA_EditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user modify view settings custom styles and behaviors..
        /// </summary>
        internal static string SA_EditViewDesc {
            get {
                return ResourceManager.GetString("SA_EditViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit widget source.
        /// </summary>
        internal static string SA_EditWidgetSrc {
            get {
                return ResourceManager.GetString("SA_EditWidgetSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to edit widget source file..
        /// </summary>
        internal static string SA_EditWidgetSrcDesc {
            get {
                return ResourceManager.GetString("SA_EditWidgetSrcDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export page data.
        /// </summary>
        internal static string SA_ExportPageData {
            get {
                return ResourceManager.GetString("SA_ExportPageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to export and download page data..
        /// </summary>
        internal static string SA_ExportPageDataDesc {
            get {
                return ResourceManager.GetString("SA_ExportPageDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export user preferences.
        /// </summary>
        internal static string SA_ExportWidgetData {
            get {
                return ResourceManager.GetString("SA_ExportWidgetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to export and download widget user preferences data..
        /// </summary>
        internal static string SA_ExportWidgetDataDesc {
            get {
                return ResourceManager.GetString("SA_ExportWidgetDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File manager.
        /// </summary>
        internal static string SA_FileMan {
            get {
                return ResourceManager.GetString("SA_FileMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow using the file manager to manage site resources.
        /// </summary>
        internal static string SA_FileManDesc {
            get {
                return ResourceManager.GetString("SA_FileManDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import page data.
        /// </summary>
        internal static string SA_ImportPageData {
            get {
                return ResourceManager.GetString("SA_ImportPageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow uploading page data file to create new page..
        /// </summary>
        internal static string SA_ImportPageDataDesc {
            get {
                return ResourceManager.GetString("SA_ImportPageDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import user preferences.
        /// </summary>
        internal static string SA_ImportWidgetData {
            get {
                return ResourceManager.GetString("SA_ImportWidgetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow uploading widget user preferences data file to add widget to page..
        /// </summary>
        internal static string SA_ImportWidgetDataDesc {
            get {
                return ResourceManager.GetString("SA_ImportWidgetDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List files.
        /// </summary>
        internal static string SA_ListFiles {
            get {
                return ResourceManager.GetString("SA_ListFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to list files from server..
        /// </summary>
        internal static string SA_ListFilesDesc {
            get {
                return ResourceManager.GetString("SA_ListFilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List paths.
        /// </summary>
        internal static string SA_ListPaths {
            get {
                return ResourceManager.GetString("SA_ListPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to list paths from server..
        /// </summary>
        internal static string SA_ListPathsDesc {
            get {
                return ResourceManager.GetString("SA_ListPathsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string SA_Localization {
            get {
                return ResourceManager.GetString("SA_Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can localize the pages and contents..
        /// </summary>
        internal static string SA_LocalizationDesc {
            get {
                return ResourceManager.GetString("SA_LocalizationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management base.
        /// </summary>
        internal static string SA_Managementbase {
            get {
                return ResourceManager.GetString("SA_Managementbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permissions.
        /// </summary>
        internal static string SA_ManagePermissions {
            get {
                return ResourceManager.GetString("SA_ManagePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow assigning permissions to role..
        /// </summary>
        internal static string SA_ManagePermissions_Desc {
            get {
                return ResourceManager.GetString("SA_ManagePermissions_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Roles.
        /// </summary>
        internal static string SA_ManageRoles {
            get {
                return ResourceManager.GetString("SA_ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to manage the role..
        /// </summary>
        internal static string SA_ManageRolesDesc {
            get {
                return ResourceManager.GetString("SA_ManageRolesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage site settings.
        /// </summary>
        internal static string SA_ManageSiteSettings {
            get {
                return ResourceManager.GetString("SA_ManageSiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to change web site common settings..
        /// </summary>
        internal static string SA_ManageSiteSettingsDesc {
            get {
                return ResourceManager.GetString("SA_ManageSiteSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string SA_ManageUsers {
            get {
                return ResourceManager.GetString("SA_ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to access the security control panel.
        /// </summary>
        internal static string SA_ManageUsersDesc {
            get {
                return ResourceManager.GetString("SA_ManageUsersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark spammers.
        /// </summary>
        internal static string SA_Markspammer {
            get {
                return ResourceManager.GetString("SA_Markspammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user can mark the comments as spam..
        /// </summary>
        internal static string SA_MarkspammerDesc {
            get {
                return ResourceManager.GetString("SA_MarkspammerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change position.
        /// </summary>
        internal static string SA_MoveChange {
            get {
                return ResourceManager.GetString("SA_MoveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow moving page to new position.
        /// </summary>
        internal static string SA_MoveChangeDesc {
            get {
                return ResourceManager.GetString("SA_MoveChangeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move files and paths.
        /// </summary>
        internal static string SA_MoveFilesAndPaths {
            get {
                return ResourceManager.GetString("SA_MoveFilesAndPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow moving files or paths to new destinations.
        /// </summary>
        internal static string SA_MoveFilesAndPathsDesc {
            get {
                return ResourceManager.GetString("SA_MoveFilesAndPathsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop Widgets.
        /// </summary>
        internal static string SA_MoveWidget {
            get {
                return ResourceManager.GetString("SA_MoveWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to drag and drop Widget on page..
        /// </summary>
        internal static string SA_MoveWidgetDesc {
            get {
                return ResourceManager.GetString("SA_MoveWidgetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page manager.
        /// </summary>
        internal static string SA_PageMan {
            get {
                return ResourceManager.GetString("SA_PageMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow using Page Manager to manage all pages in web site..
        /// </summary>
        internal static string SA_PageManDesc {
            get {
                return ResourceManager.GetString("SA_PageManDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string SA_PAGES {
            get {
                return ResourceManager.GetString("SA_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove roles from user.
        /// </summary>
        internal static string SA_RemoveRolesFromUser {
            get {
                return ResourceManager.GetString("SA_RemoveRolesFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows removing roles from users..
        /// </summary>
        internal static string SA_RemoveRolesFromUserDesc {
            get {
                return ResourceManager.GetString("SA_RemoveRolesFromUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove uploaded packages.
        /// </summary>
        internal static string SA_RemoveUploadPackage {
            get {
                return ResourceManager.GetString("SA_RemoveUploadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can remove the uploaded packages..
        /// </summary>
        internal static string SA_RemoveUploadPackageDesc {
            get {
                return ResourceManager.GetString("SA_RemoveUploadPackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit robot.txt.
        /// </summary>
        internal static string SA_Robot {
            get {
                return ResourceManager.GetString("SA_Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to edit the robot.txt file..
        /// </summary>
        internal static string SA_RobotDesc {
            get {
                return ResourceManager.GetString("SA_RobotDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string SA_SECURITY {
            get {
                return ResourceManager.GetString("SA_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp settings.
        /// </summary>
        internal static string SA_SMTPSettings {
            get {
                return ResourceManager.GetString("SA_SMTPSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can change the SMTP settings..
        /// </summary>
        internal static string SA_SMTPSettingsDesc {
            get {
                return ResourceManager.GetString("SA_SMTPSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theming.
        /// </summary>
        internal static string SA_Theming {
            get {
                return ResourceManager.GetString("SA_Theming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle widget state.
        /// </summary>
        internal static string SA_ToggleWidget {
            get {
                return ResourceManager.GetString("SA_ToggleWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow collapsing or expanding widgets.
        /// </summary>
        internal static string SA_ToggleWidgetDesc {
            get {
                return ResourceManager.GetString("SA_ToggleWidgetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files.
        /// </summary>
        internal static string SA_UploadFiles {
            get {
                return ResourceManager.GetString("SA_UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow uploading file to the server..
        /// </summary>
        internal static string SA_UploadFilesDesc {
            get {
                return ResourceManager.GetString("SA_UploadFilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload packages.
        /// </summary>
        internal static string SA_UploadPackage {
            get {
                return ResourceManager.GetString("SA_UploadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can view and upload packages..
        /// </summary>
        internal static string SA_UploadPackageDesc {
            get {
                return ResourceManager.GetString("SA_UploadPackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View website list.
        /// </summary>
        internal static string SA_ViewWebsiteList {
            get {
                return ResourceManager.GetString("SA_ViewWebsiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows users can view the websites list..
        /// </summary>
        internal static string SA_ViewWebsiteListDesc {
            get {
                return ResourceManager.GetString("SA_ViewWebsiteListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web resource system.
        /// </summary>
        internal static string SA_WebResSystem {
            get {
                return ResourceManager.GetString("SA_WebResSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webs.
        /// </summary>
        internal static string SA_Webs {
            get {
                return ResourceManager.GetString("SA_Webs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget manager.
        /// </summary>
        internal static string SA_WidgetMan {
            get {
                return ResourceManager.GetString("SA_WidgetMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow using Widget Manager to install,upload,remove and edit widgets..
        /// </summary>
        internal static string SA_WidgetManDesc {
            get {
                return ResourceManager.GetString("SA_WidgetManDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wdigets.
        /// </summary>
        internal static string SA_Widgets {
            get {
                return ResourceManager.GetString("SA_Widgets", resourceCulture);
            }
        }
    }
}
