//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputHolders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputHolders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InputHolders", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address line1.
        /// </summary>
        internal static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address line2.
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password again.
        /// </summary>
        internal static string ConfirmPwd {
            get {
                return ResourceManager.GetString("ConfirmPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the fax number.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the {0}.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the cellphone number.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter some thing to search.
        /// </summary>
        internal static string SearchHolder {
            get {
                return ResourceManager.GetString("SearchHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is 25.
        /// </summary>
        internal static string Smtp_Port {
            get {
                return ResourceManager.GetString("Smtp_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp service login passowd.
        /// </summary>
        internal static string Smtp_Pwd {
            get {
                return ResourceManager.GetString("Smtp_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default sender for all system email..
        /// </summary>
        internal static string Smtp_Sender {
            get {
                return ResourceManager.GetString("Smtp_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.e: smtp.domain.com.
        /// </summary>
        internal static string Smtp_Server {
            get {
                return ResourceManager.GetString("Smtp_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp service login name.
        /// </summary>
        internal static string Smtp_Usr {
            get {
                return ResourceManager.GetString("Smtp_Usr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the telephone number.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name or email.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user name to search.
        /// </summary>
        internal static string UsrSearchHolder {
            get {
                return ResourceManager.GetString("UsrSearchHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter web title here.ie:Acme Crop,My awesome blog.
        /// </summary>
        internal static string WebTitleHolder {
            get {
                return ResourceManager.GetString("WebTitleHolder", resourceCulture);
            }
        }
    }
}
