//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Security {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Security() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Security", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accessible roles.
        /// </summary>
        internal static string AccessRoles {
            get {
                return ResourceManager.GetString("AccessRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow anonymous.
        /// </summary>
        internal static string AllowAnonymous {
            get {
                return ResourceManager.GetString("AllowAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePwd {
            get {
                return ResourceManager.GetString("ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientID.
        /// </summary>
        internal static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret.
        /// </summary>
        internal static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPwd {
            get {
                return ResourceManager.GetString("ConfirmPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to your {0} account.
        /// </summary>
        internal static string ConnectFormat {
            get {
                return ResourceManager.GetString("ConnectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer key.
        /// </summary>
        internal static string ConsumerKey {
            get {
                return ResourceManager.GetString("ConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer secret.
        /// </summary>
        internal static string ConsumerSecret {
            get {
                return ResourceManager.GetString("ConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        internal static string CreateUsr {
            get {
                return ResourceManager.GetString("CreateUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email has been sent to {0} please check your mailbox..
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget your password?.
        /// </summary>
        internal static string ForgetPwd {
            get {
                return ResourceManager.GetString("ForgetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full permissions.
        /// </summary>
        internal static string FullPerms {
            get {
                return ResourceManager.GetString("FullPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging on.
        /// </summary>
        internal static string LoggingOn {
            get {
                return ResourceManager.GetString("LoggingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with other network account.
        /// </summary>
        internal static string LoginWithOAuth {
            get {
                return ResourceManager.GetString("LoginWithOAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with {0}.
        /// </summary>
        internal static string LoginWith_Format {
            get {
                return ResourceManager.GetString("LoginWith_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPwd {
            get {
                return ResourceManager.GetString("NewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OldPwd {
            get {
                return ResourceManager.GetString("OldPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive password.
        /// </summary>
        internal static string ReceivePwd {
            get {
                return ResourceManager.GetString("ReceivePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register email.
        /// </summary>
        internal static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload all permissions.
        /// </summary>
        internal static string ReloadPerms {
            get {
                return ResourceManager.GetString("ReloadPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scropes.
        /// </summary>
        internal static string Scropes {
            get {
                return ResourceManager.GetString("Scropes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email.
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System roles.
        /// </summary>
        internal static string SysRoles {
            get {
                return ResourceManager.GetString("SysRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        internal static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User manager.
        /// </summary>
        internal static string UsrMgr {
            get {
                return ResourceManager.GetString("UsrMgr", resourceCulture);
            }
        }
    }
}
