//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SEO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SEO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SEO", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt missing in img.
        /// </summary>
        internal static string Alt_Missing {
            get {
                return ResourceManager.GetString("Alt_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In image tags,put the alt attribute to describe the image..
        /// </summary>
        internal static string Alt_Missing_Sugg {
            get {
                return ResourceManager.GetString("Alt_Missing_Sugg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis report.
        /// </summary>
        internal static string AnalysisReport {
            get {
                return ResourceManager.GetString("AnalysisReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length.
        /// </summary>
        internal static string DescLen {
            get {
                return ResourceManager.GetString("DescLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current is {0} characters.Keep it up to 150 characters.
        /// </summary>
        internal static string DescLen_Sugg {
            get {
                return ResourceManager.GetString("DescLen_Sugg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description tag.
        /// </summary>
        internal static string DescTag {
            get {
                return ResourceManager.GetString("DescTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing description tag. Every page should be have a description tag.
        /// </summary>
        internal static string DescTag_Unvalid {
            get {
                return ResourceManager.GetString("DescTag_Unvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1 tag.
        /// </summary>
        internal static string H1 {
            get {
                return ResourceManager.GetString("H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every page should be at less and only has an h1 tag..
        /// </summary>
        internal static string H1_Unvalid {
            get {
                return ResourceManager.GetString("H1_Unvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2 tag.
        /// </summary>
        internal static string H2 {
            get {
                return ResourceManager.GetString("H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page content should be has h2 tags..
        /// </summary>
        internal static string H2_Unvalid {
            get {
                return ResourceManager.GetString("H2_Unvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords tag length.
        /// </summary>
        internal static string KeywordsLen {
            get {
                return ResourceManager.GetString("KeywordsLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords tag.
        /// </summary>
        internal static string KeywordsTag {
            get {
                return ResourceManager.GetString("KeywordsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing keyword tag.Every page should be has keywords..
        /// </summary>
        internal static string Keywords_Missing {
            get {
                return ResourceManager.GetString("Keywords_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current is {0} characters. Key it up to 10 words or 255 characters..
        /// </summary>
        internal static string Keywords_Sugg {
            get {
                return ResourceManager.GetString("Keywords_Sugg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading time.
        /// </summary>
        internal static string LoadingTime {
            get {
                return ResourceManager.GetString("LoadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of links.
        /// </summary>
        internal static string NumOfLinks {
            get {
                return ResourceManager.GetString("NumOfLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too more link elements in the page.The links must be less then 100..
        /// </summary>
        internal static string NumOfLinks_Unvalid {
            get {
                return ResourceManager.GetString("NumOfLinks_Unvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length.
        /// </summary>
        internal static string TitleLen {
            get {
                return ResourceManager.GetString("TitleLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current is {0} characters. Please keep the title length up to 11 words or 70 characters.
        /// </summary>
        internal static string TitleLen_Sugg {
            get {
                return ResourceManager.GetString("TitleLen_Sugg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title tag.
        /// </summary>
        internal static string TitleTag {
            get {
                return ResourceManager.GetString("TitleTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing title tag. Every page should be have a title tag.
        /// </summary>
        internal static string TitleTag_Unvalid {
            get {
                return ResourceManager.GetString("TitleTag_Unvalid", resourceCulture);
            }
        }
    }
}
