//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Social {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Social() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Social", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity streams.
        /// </summary>
        internal static string ActivityStreams {
            get {
                return ResourceManager.GetString("ActivityStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a message....
        /// </summary>
        internal static string CommentHolder {
            get {
                return ResourceManager.GetString("CommentHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to your {0} account.
        /// </summary>
        internal static string ConnectFormat {
            get {
                return ResourceManager.GetString("ConnectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to.
        /// </summary>
        internal static string ConnectTo {
            get {
                return ResourceManager.GetString("ConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        internal static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follows.
        /// </summary>
        internal static string Follows {
            get {
                return ResourceManager.GetString("Follows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile connections.
        /// </summary>
        internal static string ProfileConnections {
            get {
                return ResourceManager.GetString("ProfileConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies.
        /// </summary>
        internal static string Replies {
            get {
                return ResourceManager.GetString("Replies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reposts.
        /// </summary>
        internal static string Reposts {
            get {
                return ResourceManager.GetString("Reposts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        internal static string Shares {
            get {
                return ResourceManager.GetString("Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        internal static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string _Self {
            get {
                return ResourceManager.GetString("_Self", resourceCulture);
            }
        }
    }
}
