//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Validations", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the register email and password to vaildate..
        /// </summary>
        internal static string AccountConnection {
            get {
                return ResourceManager.GetString("AccountConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password again..
        /// </summary>
        internal static string ConfirmPwd {
            get {
                return ResourceManager.GetString("ConfirmPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been registered..
        /// </summary>
        internal static string EmailRegisted {
            get {
                return ResourceManager.GetString("EmailRegisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is exists..
        /// </summary>
        internal static string Exists_Format {
            get {
                return ResourceManager.GetString("Exists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a vaild integer value.
        /// </summary>
        internal static string IntVal {
            get {
                return ResourceManager.GetString("IntVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {1} characters long..
        /// </summary>
        internal static string Length_Format {
            get {
                return ResourceManager.GetString("Length_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be between {1} ~ {2} characters..
        /// </summary>
        internal static string LenRange_Format {
            get {
                return ResourceManager.GetString("LenRange_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be composed of letters and numbers..
        /// </summary>
        internal static string LetterAndNumRegex_Format {
            get {
                return ResourceManager.GetString("LetterAndNumRegex_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a vaild max length value.
        /// </summary>
        internal static string MaxLenVal {
            get {
                return ResourceManager.GetString("MaxLenVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not exists..
        /// </summary>
        internal static string NotExists_Format {
            get {
                return ResourceManager.GetString("NotExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} not found..
        /// </summary>
        internal static string NotFound_Format {
            get {
                return ResourceManager.GetString("NotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a viald number value.
        /// </summary>
        internal static string NumVal {
            get {
                return ResourceManager.GetString("NumVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the same password as above.
        /// </summary>
        internal static string Password_Equal {
            get {
                return ResourceManager.GetString("Password_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change the password.The password is incorrect..
        /// </summary>
        internal static string Password_Incorrect {
            get {
                return ResourceManager.GetString("Password_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least {0} charachter long..
        /// </summary>
        internal static string PwdLen_Format {
            get {
                return ResourceManager.GetString("PwdLen_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capticha key unvalidate..
        /// </summary>
        internal static string reCapticha_UnvalidKey {
            get {
                return ResourceManager.GetString("reCapticha_UnvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require.
        /// </summary>
        internal static string Require {
            get {
                return ResourceManager.GetString("Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required.
        /// </summary>
        internal static string Required_Format {
            get {
                return ResourceManager.GetString("Required_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name must be at least {0} charachter long..
        /// </summary>
        internal static string UserNameLen_Format {
            get {
                return ResourceManager.GetString("UserNameLen_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name must be composed of letters and numbers..
        /// </summary>
        internal static string UserName_Regex {
            get {
                return ResourceManager.GetString("UserName_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not use {0} as user name,because this name is reserved..
        /// </summary>
        internal static string UserName_Reserved {
            get {
                return ResourceManager.GetString("UserName_Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid {0}.
        /// </summary>
        internal static string Valid_Format {
            get {
                return ResourceManager.GetString("Valid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter expression is not valid.
        /// </summary>
        internal static string ViewFilter {
            get {
                return ResourceManager.GetString("ViewFilter", resourceCulture);
            }
        }
    }
}
