//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Widgets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Widgets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Widgets", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding widget ....
        /// </summary>
        internal static string AddingWidget {
            get {
                return ResourceManager.GetString("AddingWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto play.
        /// </summary>
        internal static string AutoPlay {
            get {
                return ResourceManager.GetString("AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the widget in following list and drop to the page.
        /// </summary>
        internal static string DragToPage {
            get {
                return ResourceManager.GetString("DragToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating.
        /// </summary>
        internal static string Floating {
            get {
                return ResourceManager.GetString("Floating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force refresh.
        /// </summary>
        internal static string ForceRefresh {
            get {
                return ResourceManager.GetString("ForceRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the header icon url.
        /// </summary>
        internal static string IconHolder {
            get {
                return ResourceManager.GetString("IconHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the widget title link url.
        /// </summary>
        internal static string LinkHolder {
            get {
                return ResourceManager.GetString("LinkHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximized.
        /// </summary>
        internal static string Maximized {
            get {
                return ResourceManager.GetString("Maximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimized.
        /// </summary>
        internal static string Minimized {
            get {
                return ResourceManager.GetString("Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        internal static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize links.
        /// </summary>
        internal static string OrganizeLinks {
            get {
                return ResourceManager.GetString("OrganizeLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show border.
        /// </summary>
        internal static string ShowBorder {
            get {
                return ResourceManager.GetString("ShowBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show header.
        /// </summary>
        internal static string ShowHeader {
            get {
                return ResourceManager.GetString("ShowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in.
        /// </summary>
        internal static string ShowIn {
            get {
                return ResourceManager.GetString("ShowIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in all pages.
        /// </summary>
        internal static string ShowInAllPages {
            get {
                return ResourceManager.GetString("ShowInAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in descendants.
        /// </summary>
        internal static string ShowInDescendants {
            get {
                return ResourceManager.GetString("ShowInDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in own page.
        /// </summary>
        internal static string ShowInOwnPage {
            get {
                return ResourceManager.GetString("ShowInOwnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string Toggle {
            get {
                return ResourceManager.GetString("Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No background.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using.
        /// </summary>
        internal static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
    }
}
