//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Installations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Installations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Installations", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept and continue.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting database ....
        /// </summary>
        internal static string ConnectingDb {
            get {
                return ResourceManager.GetString("ConnectingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the administrator account.
        /// </summary>
        internal static string CreateAdmin {
            get {
                return ResourceManager.GetString("CreateAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating administrator.
        /// </summary>
        internal static string CreatingAdmin {
            get {
                return ResourceManager.GetString("CreatingAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database ....
        /// </summary>
        internal static string CreatingDB {
            get {
                return ResourceManager.GetString("CreatingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the first web ....
        /// </summary>
        internal static string CreatingWeb {
            get {
                return ResourceManager.GetString("CreatingWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Authentication.
        /// </summary>
        internal static string DBAuth {
            get {
                return ResourceManager.GetString("DBAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Engine.
        /// </summary>
        internal static string DbEngine {
            get {
                return ResourceManager.GetString("DbEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is exists.Please drop the database or change your connection settings..
        /// </summary>
        internal static string DBExists {
            get {
                return ResourceManager.GetString("DBExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        internal static string DBName {
            get {
                return ResourceManager.GetString("DBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the database name.
        /// </summary>
        internal static string DbNameHolder {
            get {
                return ResourceManager.GetString("DbNameHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database name is required..
        /// </summary>
        internal static string DbNameRequired {
            get {
                return ResourceManager.GetString("DbNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter website.
        /// </summary>
        internal static string EnterWebsite {
            get {
                return ResourceManager.GetString("EnterWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string FullTrust {
            get {
                return ResourceManager.GetString("FullTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto DotNetAge official website.
        /// </summary>
        internal static string GoDNA {
            get {
                return ResourceManager.GetString("GoDNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install start kit.
        /// </summary>
        internal static string InstallStartKit {
            get {
                return ResourceManager.GetString("InstallStartKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a solution below to install to current web site..
        /// </summary>
        internal static string InstallTmplToWeb {
            get {
                return ResourceManager.GetString("InstallTmplToWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string MediumTrust {
            get {
                return ResourceManager.GetString("MediumTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My web.
        /// </summary>
        internal static string MyWeb {
            get {
                return ResourceManager.GetString("MyWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Pwd {
            get {
                return ResourceManager.GetString("Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database login password.
        /// </summary>
        internal static string PwdHolder {
            get {
                return ResourceManager.GetString("PwdHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required..
        /// </summary>
        internal static string PwdRequired {
            get {
                return ResourceManager.GetString("PwdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick start.
        /// </summary>
        internal static string Quickstart {
            get {
                return ResourceManager.GetString("Quickstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the license below then click the &quot;Accept&quot; button to start installation.
        /// </summary>
        internal static string ReadBefore {
            get {
                return ResourceManager.GetString("ReadBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting.
        /// </summary>
        internal static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup the database.
        /// </summary>
        internal static string SetupDB {
            get {
                return ResourceManager.GetString("SetupDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup your first web.
        /// </summary>
        internal static string SetupFirstWeb {
            get {
                return ResourceManager.GetString("SetupFirstWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string SrvName {
            get {
                return ResourceManager.GetString("SrvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the server name or IP.
        /// </summary>
        internal static string SrvNameHolder {
            get {
                return ResourceManager.GetString("SrvNameHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server name is required..
        /// </summary>
        internal static string SrvRequired {
            get {
                return ResourceManager.GetString("SrvRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation  has completed successfully..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust level.
        /// </summary>
        internal static string TrustLevel {
            get {
                return ResourceManager.GetString("TrustLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unknow error ocour.
        /// </summary>
        internal static string UnknowError {
            get {
                return ResourceManager.GetString("UnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string Usr {
            get {
                return ResourceManager.GetString("Usr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database login name.
        /// </summary>
        internal static string UsrHolder {
            get {
                return ResourceManager.GetString("UsrHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is required.
        /// </summary>
        internal static string UsrRequired {
            get {
                return ResourceManager.GetString("UsrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating.
        /// </summary>
        internal static string Validating {
            get {
                return ResourceManager.GetString("Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the web site description.
        /// </summary>
        internal static string WebDescHolder {
            get {
                return ResourceManager.GetString("WebDescHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the website ,this text will set in the Meta tag in each page header part. If this option set, it will make the pages more searchable..
        /// </summary>
        internal static string WebDescNotes {
            get {
                return ResourceManager.GetString("WebDescNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the web site title.
        /// </summary>
        internal static string WebTitleHolder {
            get {
                return ResourceManager.GetString("WebTitleHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the web site&apos;s title,this title will display on the window title and use for search engine&apos;s search result title..
        /// </summary>
        internal static string WebTitleNotes {
            get {
                return ResourceManager.GetString("WebTitleNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DotNetAge3 installation.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Authentication.
        /// </summary>
        internal static string WinAuth {
            get {
                return ResourceManager.GetString("WinAuth", resourceCulture);
            }
        }
    }
}
